"""Tests for generated shell completion scripts.

The completion scripts are generated by ``scripts/generate_completions.py``
from the live argparse parser.  A drift guard regenerates them in a temporary
directory and asserts they are byte-for-byte identical to the committed files,
so any new subcommand or flag must be accompanied by a regeneration of the
completion scripts.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from claude_wiki._completions import (
    COMPLETION_NAMES,
    generate_all,
    get_parser,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
COMPLETIONS_DIR = REPO_ROOT / "completions"
GENERATOR_SCRIPT = REPO_ROOT / "scripts" / "generate_completions.py"


@pytest.mark.parametrize("name", COMPLETION_NAMES)
def test_completion_script_exists_and_is_not_empty(name: str) -> None:
    """Every expected completion script exists and has content."""
    path = COMPLETIONS_DIR / name
    assert path.exists(), f"Missing completion script: {path}"
    assert path.stat().st_size > 0, f"Completion script is empty: {path}"


def _read_script(name: str) -> str:
    return (COMPLETIONS_DIR / name).read_text(encoding="utf-8")


def test_bash_completion_contains_all_top_level_commands() -> None:
    """The bash script completes every top-level subcommand."""
    parser = get_parser()
    script = _read_script("claude-wiki.bash")
    top = list(parser._subparsers._group_actions[0].choices.keys())  # type: ignore[attr-defined]
    for command in top:
        assert command in script, f"bash completion missing subcommand: {command}"


def test_zsh_completion_contains_all_top_level_commands() -> None:
    """The zsh script completes every top-level subcommand."""
    parser = get_parser()
    script = _read_script("claude-wiki.zsh")
    top = list(parser._subparsers._group_actions[0].choices.keys())  # type: ignore[attr-defined]
    for command in top:
        assert command in script, f"zsh completion missing subcommand: {command}"


def test_fish_completion_contains_all_top_level_commands() -> None:
    """The fish script completes every top-level subcommand."""
    parser = get_parser()
    script = _read_script("claude-wiki.fish")
    top = list(parser._subparsers._group_actions[0].choices.keys())  # type: ignore[attr-defined]
    for command in top:
        assert command in script, f"fish completion missing subcommand: {command}"


def test_bash_completion_contains_registry_subcommands() -> None:
    """The bash script completes the nested registry subcommands."""
    script = _read_script("claude-wiki.bash")
    for sub in ("list", "show", "remove", "clean"):
        assert sub in script, f"bash completion missing registry subcommand: {sub}"


def test_generator_script_runs_without_error() -> None:
    """The standalone generator script exits 0 and writes the three files."""
    result = subprocess.run(
        [sys.executable, str(GENERATOR_SCRIPT), "--check"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr


def test_completion_scripts_do_not_drift(tmp_path: Path) -> None:
    """Regenerating the scripts must match the committed files exactly."""
    generate_all(tmp_path)

    for name in COMPLETION_NAMES:
        expected = COMPLETIONS_DIR / name
        generated = tmp_path / name
        assert generated.exists(), f"Generator did not produce {name}"
        assert generated.read_bytes() == expected.read_bytes(), (
            f"Completion script drifted: {name}. "
            f"Run `uv run python scripts/generate_completions.py` to regenerate."
        )
